### ISSUE TITLE
GPRC exception is thrown on run

### ISSUE THREAD

**Issue by bradleywolinski** [procro04/clue-less#2]
## Effected Branch and Version
f67a38fcd86968c7c453d82239a118a0ec4ff9e1

## Issue
On a fresh pull of development branch, an exception is being thrown regarding GPRC, while this is most likely a configuration issue we should try to document and resolve it.
![image](https://github.com/procro04/clue-less/assets/83616477/a9e1e2f5-efd3-4fed-8e90-b81223d8470f)

**Comment by icanhearyousmile** [comment]
This happens when the startup projects are not configured.

Go to the Solution Level, right click and select "Manage Startup Projects"

When it opens, select "Multiple Startup Projects", and then Clue-Less and Clue-Less-Server. For Action, select "Start". This will launch both projects correctly when you run the solution. :) I have uploaded this video to hopefully show how to do it easily. Let me know if you have any other issues.

https://github.com/procro04/clue-less/assets/35151483/3ff8cd91-dafa-425e-be3b-3e617626c2fc

**Comment by bradleywolinski** [comment]
Worked like a charm! Doesn't look like that gets saved with the .sln so we will just need to remain mindful of that.
![image](https://github.com/procro04/clue-less/assets/83616477/2c826a01-6a90-4731-a58d-e395f9380837)

**Comment by icanhearyousmile** [comment]
Correct, it doesn't save. I did update the Readme file, though, and I can put together a "Setup" Wiki entry :)
